version: 2
jobs:
    build:
        docker:
            - image: circleci/node:12.9.1-browsers
        steps:
            - checkout
            - run: "yarn install"
            - run: "npm run deploy"